run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  exclude-dirs:
    - vendor/

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - gocritic
    - gocyclo
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - lll
    - nakedret
    - copyloopvar
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  mnd:
    settings:
      mnd:
        checks: 
          - argument
          - case
          - condition
          - operation
          - return
        ignored-numbers:
          - '0'
          - '1'
          - '2'
          - '8080'
          - '30'
          - '100'
          - '10'
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
  wsl:
    allow-cuddle-declarations: true
    force-case-trailing-whitespace: 0

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - wsl
    - path: internal/proxy/proxy.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - wsl

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true 