run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - bodyclose
    - gocritic
    - gocyclo
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - gosqlrows
    - gostructcheck
    - gosystemd
    - gotype
    - gotypex
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        checks: assignment,case,condition,operation,return,argument
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral
      - wrapperFunc
      - dupImport
      - ifElseChain
      - octalLiteral

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: internal/proxy/proxy.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

  sort-results: true 